"""initial facility registry: facility + bed_count (docs/02-data-model.md §2.1-2.2)

Hand-written (not autogenerated) so the PostgreSQL enum types and the array-of-enum column
are created in a known order — Alembic's autogenerate is unreliable for enum arrays.

Revision ID: 0001_facility_registry
Revises:
Create Date: 2026-06-28
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_facility_registry"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Enum types, created explicitly up front. Labels are the lowercase values that the ORM
# (via pg_enum's values_callable) and the API use. Names match app/db/models/enums.py.
TIER = postgresql.ENUM("tertiary", "secondary", "primary", name="tier")
BEDTYPE = postgresql.ENUM("general", "icu", "maternity_specialist", name="bedtype")
DATASOURCE = postgresql.ENUM(
    "simulation", "facility_management", "national_emr", "hl7_fhir", name="datasource"
)


def upgrade() -> None:
    bind = op.get_bind()
    TIER.create(bind, checkfirst=True)
    BEDTYPE.create(bind, checkfirst=True)
    DATASOURCE.create(bind, checkfirst=True)

    op.create_table(
        "facility",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("latitude", sa.Numeric(9, 6), nullable=False),
        sa.Column("longitude", sa.Numeric(9, 6), nullable=False),
        sa.Column("tier", postgresql.ENUM(name="tier", create_type=False), nullable=False),
        sa.Column(
            "supported_bed_types",
            postgresql.ARRAY(postgresql.ENUM(name="bedtype", create_type=False)),
            nullable=False,
        ),
        sa.Column("contact_phone", sa.Text(), nullable=False),
        sa.Column(
            "active_data_source",
            postgresql.ENUM(name="datasource", create_type=False),
            server_default="simulation",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_facility_name"),
    )

    op.create_table(
        "bed_count",
        sa.Column(
            "id",
            postgresql.UUID(as_uuid=True),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("facility_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("bed_type", postgresql.ENUM(name="bedtype", create_type=False), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["facility_id"], ["facility.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("facility_id", "bed_type", name="uq_bed_count_facility_bedtype"),
        sa.CheckConstraint("available >= 0", name="ck_bed_count_available_nonneg"),
        sa.CheckConstraint("available <= capacity", name="ck_bed_count_available_le_capacity"),
    )


def downgrade() -> None:
    op.drop_table("bed_count")
    op.drop_table("facility")
    DATASOURCE.drop(op.get_bind(), checkfirst=True)
    BEDTYPE.drop(op.get_bind(), checkfirst=True)
    TIER.drop(op.get_bind(), checkfirst=True)
